### ISSUE TITLE
Adress "00000000" gets formatted as "0"

### ISSUE THREAD

**Issue by Luz** [Luz/hexdino#14]
![octocat](https://raw.githubusercontent.com/Luz/sega-rom-reader/master/pics/pic4.jpg)
I think it gets formatted like this as soon as the number to be formatted is 15(dec) or smaller

**Comment by dbrgn** [comment]
That's strange, it should work...

Here's the line: https://github.com/Luz/hexdino/blob/dcf3ca7e98e0a35aa196588d17706db854a85d77/src/draw.rs#L26

The code should work:

https://play.rust-lang.org/?gist=5fbcf38a46dbc81f026efaf46397f81e&version=stable&mode=debug&edition=2015

Maybe printw does something fancy with the output.

**Comment by Luz** [comment]
Thanks, you are right, it works!
It did not work in xfce4-terminal but it works in xterm and in urxvt.
