### ISSUE TITLE
Huge CPU and memory usage when opening big files

### ISSUE THREAD

**Issue by rnestler** [Luz/hexdino#19]
When opening big files (ie. images) the CPU usage is 100% while loading the file completely to RAM. Afterwards hexdino uses the size of the file as RAM.

Maybe it would make sense to only load parts of the file into RAM or use something like [memmap](https://docs.rs/memmap/0.7.0/memmap/) to let the operating system handle that.

**Comment by Luz** [comment]
I have just looked at the issue and tried to implement the desired functionality, but then I realized:
- That this would add a huge amount complexity to the software
- That the benefits would be rather small in terms of ram usage and speed (Think about changing 1 byte at position 1gb of a 4gb file; this would require the library to rewrite 3gb on the disk or would use it as ram, or then extremely sophisticated code which would rather be put into an external library)
- That other well-established software require even much more ram and have also a higher loading time (Tried notepad++ on windows and default vim, maybe they are converting the bytes into their default storage method, which might not be optimal)
